### ISSUE TITLE
Actionability

### ISSUE THREAD

**Issue by samgdf** [jkrasnits/markovBTC#1]
So, do I buy when 
`([-4.0, -1.0, 3.0, 2.0, 14.0, -1.0, 5.0], 1.0)`
the number at the end is higher than 0, because that indicates the vector going up?

Really cool!

**Comment by jkrasnits** [comment]
Hey dude, yeah pretty much that 1.0 is prediction of what the % change will
be in the exchange rate from the most recent closing rate to the next days
closing rate. I have a slightly better version that I haven't pushed yet,
but its still super rough. The code is booty as well, so I'm planning on
refactoring it as soon as I get a chance. Rn I'm just seeing if I can make
something that can make remotely believable predictions.

**Comment by samgdf** [comment]
Hey man. Code does what it says it'll do, nothing to apologize for 'being booty'. Push the new version, I'm interested. I'll add PyTorch and we'll sell it to Bloomberg.

PS. You never added me as a contributor to YouBuzz. Also follow me on here.
